### ISSUE TITLE
[Feature request] Support for content diff in the float window

### ISSUE THREAD

**Issue by voldikss** [rhysd/git-messenger.vim#11]
Thanks you, this is an awesome plugin! Since I can view the specific commit history with it. It would be better that this plugin supports viewing the changed content.

Most people as well as I commonly use [vim-fugutive](https://github.com/tpope/vim-fugitive/)'s command `Gvdiff` to view the not yet staged content. Besides, we use [vim-mundo](https://github.com/simnalamburt/vim-mundo/) to view the history.

Now there might be a plugin which allow us to view the changed content within a commit. How do you think about this?

**Comment by rhysd** [comment]
I experimentally implemented this feature at [`diff`](https://github.com/rhysd/git-messenger.vim/tree/diff) branch. Setting `let g:git_messenger_include_diff = v:true` in vimrc enables it.

![demo](https://user-images.githubusercontent.com/823277/55374100-47a97080-5542-11e9-9d7e-da67aa1c0f44.gif)

**Comment by voldikss** [comment]
Cool! Thank you for quick implementation! I just tried it.

At present, the diff of all files is included in the popup window. Could it supply an option (like `let g:git_messenger_diff_all=v:false`) to load the change only for the current file? (If possible, only for current line...this might be difficult to implement)

**Comment by rhysd** [comment]
> At present, the diff of all files is included in the popup window.

Actually it was a bug of my implementation. I updated `diff` branch to show diff of the specific commit.

**Comment by voldikss** [comment]
@rhysd Sorry I didn't say it clearly before. Actually I want to say that git-messenger shows **every** file's diff content in one commit. It would be better to show only the change of current file rather than all files' change in one commit.

**Comment by rhysd** [comment]
I got your point, thanks. I agree it might be better to include diffs only related to current file. Let me have some trial

**Comment by rhysd** [comment]
I updated `diff` branch. Now type of `g:git_messenger_include_diff` is `string`, not `boolean`.

Could you try following config? It only shows diff hunks of current file.

```vim
let g:git_messenger_include_diff = 'current'
```

**Comment by voldikss** [comment]
I just tested on my PC, it totally works as expected., thank you!

Now should I  close this issue?

**Comment by rhysd** [comment]
I will close this branch when the `diff` branch is merged into master. So please remain it open.

**Comment by voldikss** [comment]
all right!

**Comment by wookayin** [comment]
Guys, this is amazing. Thanks for the great feature!

**Comment by rhysd** [comment]
I need to add a few more tests. After that, I'll merge the branch.

**Comment by rhysd** [comment]
I merged `diff` branch into `master`. Please use `master` branch for the latest. `diff` branch will be deleted soon.

Diff can be seen here: https://github.com/rhysd/git-messenger.vim/compare/9ead3f80e51a55945298ad201e7edd0b2b58d3f2..a61e73fe0928ad4d06bad4bc8fa4291afb8fcbd2
