### ISSUE TITLE
Jumping to another window

### ISSUE THREAD

**Issue by kassio** [rhysd/git-messenger.vim#12]
When opening the floating window with an existing split window the cursor is jumping to the split window:
![git-messenger](https://user-images.githubusercontent.com/120483/55404401-b9d48200-554f-11e9-870d-cf13b06e3a4e.gif)

**Comment by kassio** [comment]
I had a similar problem with neoterm before, it was solved using windows ids. In neoterm I created a hook to always come back to the same [window](https://github.com/kassio/neoterm/blob/master/autoload/neoterm.vim#L101):

```viml
call win_gotoid(a:instance.origin) " origin comes from win_getid()
```

**Comment by rhysd** [comment]
could you describe the steps to reproduce? I need to investigate what happens internally

**Comment by kassio** [comment]
Seems to be working now. Maybe something wrong on my env. Sorry for the noise.
