### ISSUE TITLE
description on "g:git_messenger_no_default_mappings" is incorrect

### ISSUE THREAD

**Issue by naoki0xff** [rhysd/git-messenger.vim#15]
I think readme & help file should be modified with following part.

At first, readme describes as follows and that is true.
> If you don't like the default mapping, set g:git_messenger_no_default_mappings to v:true in your .vimrc or init.vim and map the <Plug> mapping to your favorite key sequence.

but below lines seems to explaining opposite thing.
>g:git_messenger_no_default_mappings (Default: v:true)

>When this value is set to v:false, it does not define any key mappings. <Plug> mappings are >still defined since they don't make any conflict with existing mappings.

It should be
- (Default: **v:false**) = given default is not v:true but v:false.
- When this value is set to **v:true**, it does not .... = with v:true, there would be no default key mapping.

Thanks.

**Comment by rhysd** [comment]
Thanks for the point. The documentation is wrong. I'll update it.
