### ISSUE TITLE
<leader>gm doesn't work out-of-the-box for me.

### ISSUE THREAD

**Issue by jsatk** [rhysd/git-messenger.vim#18]
I installed via minpac.

Went to give this a try and pressed `<leader>gm` and got nothing. `:GitMessenger<CR>` works though. 

I'm on the latest Vim provided by Homebrew on macOS (8.1).

Any ideas why this wouldn't work out of the box? I checked my mappings and, as far as I can tell, I don't have anything mapped to `<leader>gm` or even `<leader>g`.

**Comment by ryanbas21** [comment]
I'll go out on a limb and say you have a conflicting mapping

**Comment by rhysd** [comment]
@jsatk 

Following command shows what `<Leader>gm` is mapped and where it was defined. Could you check the output?

```
:verbose nmap <Leader>gm
```

@ryanbas21 

Thanks for your follow up.

**Comment by jsatk** [comment]
I reinstalled and now it works. 🤔

You can prolly ignore this. 😬
