### ISSUE TITLE
Cursor doesn't move inside the popup window

### ISSUE THREAD

**Issue by ahmedelgabri** [rhysd/git-messenger.vim#19]
> Behavior of this command is depending on the situation. You can do every operations only with this mapping.
>
> - Normally, it opens a popup window with the last commit message
> - When a popup window is already open, _**it moves cursor into the window**_
> - When a cursor is within a popup window, it closes the window

`<leader>gm` open the popup properly, I can see all the info. But the cursor is not moved inside so I can't use any of the other mappings to go back/forward in history etc…

As you can see in the image, `o` creates a new line & `D` deletes the rest of the line.

![popup](https://user-images.githubusercontent.com/63876/57192274-e9035800-6f2e-11e9-91e8-823f4a9ccd05.gif)

**Comment by ahmedelgabri** [comment]
Ignore that, I thought it will do this automatically but actually, I need to switch to the popup buffer myself. Sorry for the misunderstanding.

**Comment by sfpmld** [comment]
Hello,
but README says it would have been automatic but I'm not able to make the cursor go in the popup either... How to configure this plugin to moove automatically the cursor into the popup?

**Comment by rhysd** [comment]
@ahmedelgabri 

Yeah, and if you want, please try following configuration.

```vim
let g:git_messenger_always_into_popup = v:true
```
