### ISSUE TITLE
Support colorscheme

### ISSUE THREAD

**Issue by Jomik** [rhysd/git-messenger.vim#20]
I was pondering if it is possible to use our colorscheme to choose a background color for the popup.
I use Gruvbox, which has variations of its main background color, that would be useful.
I made an issue here: https://github.com/morhetz/gruvbox/issues/278
I think [coc.nvim](https://github.com/neoclide/coc.nvim/blob/master/plugin/coc.vim#L190) uses `Pmenu` as its highlight group, which seems to work fine.

**Comment by rhysd** [comment]
You can configure it in your `init.vim` using `:hi link`.

For example:

```vim
" Header such as 'Commit:', 'Author:'
hi link gitmessengerHeader Identifier

" Commit hash at 'Commit:' header
hi link gitmessengerHash Comment

" History number at 'History:' header
hi link gitmessengerHistory Constant

" Normal color. This color is the most important
hi link gitmessengerPopupNormal CursorLine

" Color of 'end of buffer'. To hide '~' in popup window, I recommend to use the same background
" color as gitmessengerPopupNormal.
hi gitmessengerEndOfBuffer term=None guifg=None guibg=None ctermfg=None ctermbg=None
```

Which highlight group should be linked is depending on the colorscheme's palette. Please adjust highlight group names to link.

```
hi link gitmessengerXxx {favorite highlight name}
```

For instance, above configuration with [vim-color-spring-night](https://github.com/rhysd/vim-color-spring-night) is as follows:

<img width="682" alt="スクリーンショット 2019-05-06 19 43 05" src="https://user-images.githubusercontent.com/823277/57220674-34089280-7037-11e9-953b-04b88e797e88.png">

**Comment by rhysd** [comment]
I will add this to README and help files

**Comment by rhysd** [comment]
> I think coc.nvim uses Pmenu as its highlight group, which seems to work fine.

It's correct in many cases, but some colorschemes utilize vivid colors for popup menu background colors and they are not suitable for reading sentences.

**Comment by Jomik** [comment]
That's perfect, thank you for the quick response. I didn't realize that it'd be sufficient to link `gitmessengerPopupNormal` to `Pmenu` :D
