### ISSUE TITLE
Error when Calling :GitMessenger

### ISSUE THREAD

**Issue by winasforcepta** [rhysd/git-messenger.vim#22]
Hi, I got some errors after calling `:GitMessenger` function. Here is the error.
```
Error detected while processing function <SNR>112_on_exit_nvim[2]..<SNR>111_blame__after_log[21]..<SNR>111_blame__open_popup[31]..<SNR>110_popup__open[5]..<SNR>110_popup__window_size:
line    2:
E117: Unknown function: win_screenpos
Press ENTER or type command to continue
Error detected while processing function <SNR>112_on_exit_nvim[2]..<SNR>111_blame__after_log[21]..<SNR>111_blame__open_popup[31]..<SNR>110_popup__open[5]..<SNR>110_popup__window_size:
line    2:
E15: Invalid expression: win_screenpos(bufwinnr(self.opener_bufnr))
Press ENTER or type command to continue
Error detected while processing function <SNR>112_on_exit_nvim[2]..<SNR>111_blame__after_log[21]..<SNR>111_blame__open_popup[31]..<SNR>110_popup__open:
line    5:
E714: List required
Press ENTER or type command to continue
```
I'm using neovim 0.3.1. Any help is appreciated. Thank you

**Comment by rhysd** [comment]
I guess updating your Neovim version would solve this issue. I also try to fix this by checking if `win_screenpos()` exists.

**Comment by rhysd** [comment]
https://github.com/neovim/neovim/commit/b89c08901c1e619b9aeca6f109f6ba73a7be4e9f

Note: `win_screenpos` was added at Neovim v0.3.5 so it is not available on earlier version

**Comment by rhysd** [comment]
f88a675 should fix this issue. Please update to the latest and confirm the fix.

**Comment by winasforcepta** [comment]
you're right, updating neovim will fix the problem. Thank you @rhysd :smile:
great plugin btw :1st_place_medal:
