### ISSUE TITLE
Wrong cursor position after diff

### ISSUE THREAD

**Issue by petobens** [rhysd/git-messenger.vim#23]
Awesome plugin! I found one minor nit. Consider the following minimal `init.vim`:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/rhysd/git-messenger.vim

filetype plugin indent on
let g:mapleader = ','
nmap <silent> <Leader>gm <Plug>(git-messenger)
```
Now as in the GIF:
1. run `,gm` twice from a right vertical split window
2. Press `D` in the floating window to get a diff
3. Press `q` to exit the floating window
4. Now the cursor is on the left vertical split
I expect the cursor position to be preserverd.

![gitmessenger](https://user-images.githubusercontent.com/2583971/57335835-4566a300-70fa-11e9-8157-e39496ca9821.gif)

Bonus: is it possible to render diffs always below the cursor? Currently when I press `D` inside the floating window then the floating window generally moves to the upper west corner of the screen.

**Comment by rhysd** [comment]
Thank you for minimal vimrc and detailed reproducible steps with screencast. They are very helpful. I confirmed the incorrect cursor position is bug of this plugin.

**Comment by rhysd** [comment]
d62787e fixed this issue. Please update to the latest and confirm the fix.

**Comment by petobens** [comment]
Working! Thank you :)
