### ISSUE TITLE
Toggle diff

### ISSUE THREAD

**Issue by petobens** [rhysd/git-messenger.vim#24]
Is possible to toggle diffs by pressing `d` or `D` twice? i.e the first time actually reveal the diff hunks and the second time `d` or `D` is press hide them. Thanks!

**Comment by rhysd** [comment]
It would be possible by remembering the start line of diff. I will try to implement the toggle behavior

**Comment by petobens** [comment]
Awesome thanks

**Comment by rhysd** [comment]
I implemented this at 57b9bcd. Please update to the latest and try.


![demo2](https://user-images.githubusercontent.com/823277/57442383-d8ccdf00-7286-11e9-8595-08032adec1a4.gif)

**Comment by petobens** [comment]
Brilliant! Thank you :)
