### ISSUE TITLE
Don't give error when first commit is reached

### ISSUE THREAD

**Issue by petobens** [rhysd/git-messenger.vim#25]
When using `o` and `O` to move through the commit history if the last commit is reached the following message is shown:
```
git-messenger: The latest commit
```
On the other hand when the first commit is reached and `o` is pressed again the following error shows:
```
git-messenger: fatal: no such path vim/init.vim in 238b69d88d84f13a746f8be64c9b15fc736a9748 : `git ...edro/git-repos/private/dotfiles/vim/init.vim -L 360,+1 --porcelain` exited with non-zero status 128
```
Is that a feature? Isn't it better to show a message like `git-messenger: Already at oldest commit`? Thanks!

**Comment by rhysd** [comment]
To simplify logic and avoid edge cases, current policy of error handling of this plugin is 'when Git fails, this plugin fails'. And if the commit is the oldest, basic message is

```
git-messenger: No older commit found
```

Implemented [here](https://github.com/rhysd/git-messenger.vim/blob/247b421cf93ce712c975959dcd2c75e68767a089/autoload/gitmessenger/blame.vim#L39).

So I want to reproduce the 'fatal: no such path' error at first. Is the repository which caused the error public? If so, please let me know which line of which file of which commit of which repository caused the error. I'll try to reproduce it.

**Comment by rhysd** [comment]
I guess the error occurs when the file is not managed by Git. If it's correct, I can add an additional check if the file is managed by Git at first.

**Comment by petobens** [comment]
Hi sorry for the late reply. Using this file and pressing `o` twice on that line I get the error: https://github.com/petobens/dotfiles/blob/da1642d9511fa1ca00aea326ce472ed15904d836/vim/init.vim#L2350

**Comment by rhysd** [comment]
Thank you, let me have some trial

**Comment by rhysd** [comment]
I tried following steps, but I could not get the error. Is there any pre-condition?

```
git clone https://github.com/petobens/dotfiles.git && cd dotfiles
nvim vim/init.vim

:2350
:GitMessenger
```

![スクリーンショット 2019-05-13 15 50 41](https://user-images.githubusercontent.com/823277/57601209-d6c09400-7596-11e9-8dfc-438f219101d5.png)

**Comment by petobens** [comment]
Mmmm. I'll try to reproduce this consistently and let you know. Thank you very much for looking into it :)

**Comment by rhysd** [comment]
Thanks. Once I get the reason why the error happens, I could make some decision.

**Comment by goronfreeman** [comment]
I'm having this same issue. I think I might know the condition that is causing this. You can use [this](https://github.com/goronfreeman/nvimfiles/blob/master/init.vim) repo to try reproducing it. It seems like the issue is when there is only one commit for a particular line. In the file I linked, try executing `:GitMessenger` on line 1, then enter the floating window and press `o`. You should see the error message that @petobens originally reported. If you do the same thing on line 4 and keep navigating back through the commits, once you reach the oldest commit, you'll get the expected `git-messenger: No older commit  found` message instead of an error.

It might be worth noting that I'm using Neovim 0.4 prerelease with floating windows.

**Comment by goronfreeman** [comment]
I guess that isn't the only condition for triggering the issue. I just tried it on a couple other files and did not get the error. I'll post another comment if I find any sort of pattern.

**Comment by rhysd** [comment]
@goronfreeman Thank you for the information. I'll try to reproduce. Could you tell me the commit hash you could reproduce this issue in the repository? It's better to perfectly match the precondition for reproduction.

**Comment by goronfreeman** [comment]
The hash shown in the git-messenger popup is `384cd3669bf6d4a185a3c9d72c79dba58b5b924e`, then when I hit `o` to navigate back, this is the error:

```
git-messenger: fatal: no such path init.vim in ae639371fd55deee2a7cbef28bbbe90e35339a24 : `git --no-pager blame ae639371fd55deee2a7cbef28bbbe90e35339a24 /Users/hbraun/github/nvimfiles/init.vim -L 1,+1 --porcelain` exited with non-zero status 128
```

**Comment by rhysd** [comment]
Sure. Thanks

**Comment by rhysd** [comment]
I could reproduce this.

**Comment by rhysd** [comment]
I could locate the issue. This is a bug of git-messenger.vim. Currently git-messenger.vim cannot follow file renames while exploring older commits.

In the case @goronfreeman showed, the latest commit for `init.vim` is `384cd3669bf6d4a185a3c9d72c79dba58b5b924e` and the file was renamed at `ae639371fd55deee2a7cbef28bbbe90e35339a24` from `nvimrc`. So git-messenger.vim must read changes from file `nvimrc` but it still tries to read from file `init.vim`.

**Comment by rhysd** [comment]
f39748d4c8c04e96ce4359f4eb1b26adac937fae should solve this issue. Thank you for the information to solve this issue.

**Comment by petobens** [comment]
Thank you!
