### ISSUE TITLE
[Feature Request] Diff of unstaged content

### ISSUE THREAD

**Issue by voldikss** [rhysd/git-messenger.vim#26]
> git-messenger.vim is a Vim/Neovim plugin to reveal the hidden message from Git under the cursor quickly. It shows the history of commits under the cursor in popup window.

I know that this plugin is developed to display the commited messenger and blame.
Could it support diff for unstaged/uncommited content? (like what [git-p](https://github.com/iamcco/git-p.nvim) does)

**Comment by rhysd** [comment]
Could you describe more specifically? This plugin shows information of specific commit. And unstaged hunks are not related to any commit yet. 

Possible idea I can come up with is:

- When the line under the cursor is unstaged, the result of `git blame` is invalid (Commit hash is `0000000000000000000000000000000000000000` and Committer is `Not Committed Yet`). In the case, show unstaged diffs on `d`

Is this what you mean?

**Comment by rhysd** [comment]
Anyway, your idea seems to make this plugin better. Let me try to implement diff for invalid commit which is not committed yet.

**Comment by voldikss** [comment]
> When the line under the cursor is unstaged, the result of git blame is invalid (Commit hash is 0000000000000000000000000000000000000000 and Committer is Not Committed Yet). In the case, show unstaged diffs on d

Exactly what I want. Thanks!

**Comment by voldikss** [comment]
As shown in this gif. show unstaged diffs 

![Peek 2019-05-21 10-51](https://user-images.githubusercontent.com/20282795/58064928-94aada00-7bb6-11e9-89cb-9480950c9194.gif)

**Comment by rhysd** [comment]
I tried to implement:

- Show unstaged diff of current file:

![current](https://user-images.githubusercontent.com/823277/58064991-29b1d100-7bbf-11e9-8a73-b1010707017b.gif)

- Show unstaged diff of all files:

![all](https://user-images.githubusercontent.com/823277/58065002-30d8df00-7bbf-11e9-8317-f7b8a93cda2a.gif)

**Comment by voldikss** [comment]
Awesome work! Will you push it into the master soon?

**Comment by rhysd** [comment]
I added it at 73f462c. Please update to the latest and try it.
