### ISSUE TITLE
Triggering :GitMessenger changes the color of ~ in the sidebar

### ISSUE THREAD

**Issue by goronfreeman** [rhysd/git-messenger.vim#27]
This just started happening with the latest update. When you run `:GitMessenger`, all of the `~` characters in the left margin change colors in all buffers. In my case, they change from grey to white.

BEFORE
![Screen Shot 2019-05-23 at 2 58 43 PM](https://user-images.githubusercontent.com/5210483/58282434-586caa80-7d6b-11e9-97b0-1d1c96ea4544.png)
AFTER
![Screen Shot 2019-05-23 at 2 58 56 PM](https://user-images.githubusercontent.com/5210483/58282439-5acf0480-7d6b-11e9-8727-11c9e0c2a617.png)

I also removed all of my personal config to see if that changed anything, but that did not help.

**Comment by goronfreeman** [comment]
I took a look through the recent changes, and it looks like [this](https://github.com/rhysd/git-messenger.vim/blob/master/syntax/gitmessengerpopup.vim#L31) line is the cause.

**Comment by rhysd** [comment]
Thanks for reporting this. It seems bug due to 0c6f37a.

**Comment by rhysd** [comment]
I fixed this at ddab5e6. Please update to the latest.
