### ISSUE TITLE
Duplicated text in commits starting with '[]'

### ISSUE THREAD

**Issue by Mike325** [rhysd/git-messenger.vim#35]
If the commit message starts with square brackets [] opening and closing the diffs duplicate the text

Commit example:
```
Dummy commit

[Test] git messenger commit test
```

Steps:

- Create a new commit with the commit example
- Execute :GitMessenger
- Jump to gitmessenger window and reveal diff with "d" or "D"

![messenger](https://user-images.githubusercontent.com/4576770/60840336-e1f9ff80-a194-11e9-80ef-ff5a6b8f8e18.png)

![messenger2](https://user-images.githubusercontent.com/4576770/60840346-e4f4f000-a194-11e9-8fca-c55043bdd48b.png)

**Comment by rhysd** [comment]
Thank you for reporting this. It seems a weird bug of this plugin.

**Comment by rhysd** [comment]
I'm sorry for the delay. I could reproduce this.

**Comment by rhysd** [comment]
I have fixed this at 72975c9.
