### ISSUE TITLE
git-messenger seems to fail in worktrees

### ISSUE THREAD

**Issue by jsholmes** [rhysd/git-messenger.vim#37]
When I try it in a worktree I see something like:
`
git-messenger: fatal: '/usr/scratch/<snip>' is outside repository : `git --no-pager blame /usr/scratch/<snip> -L 86,+1 --porcelain` exited with non-zero status 128
`

If I do it in the main directory I don't see this issue.

**Comment by rhysd** [comment]
I found a bug that git-messenger.vim cannot find proper `.git` when worktree is put inside main repository.
