### ISSUE TITLE
Opening preview-window closes folds

### ISSUE THREAD

**Issue by Ambroisie** [rhysd/git-messenger.vim#39]
Using Vim 8.1, when git-messenger opens the preview-window on a file containing open folds, they are all closed as if I had just opened the file. I have to manually open them again to restore the view as it was before calling git-messenger.

However when I switch to the preview-window or close it using the same mapping, my folds are kept intact.

**Comment by rhysd** [comment]
I confirmed this is a bug of git-messenger.vim. Thanks for reporting.

**Comment by rhysd** [comment]
This issue should be fixed in c7d836d. Please update to the latest.
