### ISSUE TITLE
Commit hash always on new line

### ISSUE THREAD

**Issue by weilbith** [rhysd/git-messenger.vim#40]
This isn't a real problem, but also not very nice: if the `Commit: <commit-hash>` line is the longest, it does not get respected on the floating window width calculation. Instead the width is too small and I get the commit hash is on a new line. Similar goes for long `Author: <author>` lines, which also break into a new line instead of a more wide window with the full author in one line. It would be just more pretty. I add two screenshots with examples (my colorscheme it not optimal for this atm).

Commit hash on new line:
![screenshot_1574417945](https://user-images.githubusercontent.com/12543647/69418018-1de3ca80-0d1a-11ea-876d-4018fa6c5d07.png)

Author line break:
![screenshot_1574417935](https://user-images.githubusercontent.com/12543647/69418037-25a36f00-0d1a-11ea-9c18-ba092f170ac6.png)

**Comment by rhysd** [comment]
Thank you for reporting this. It sounds a bug on calculating width of the window. Let me check.

**Comment by rhysd** [comment]
I tried on my project, but could not reproduce this:

Case1: Commit hash line is the longest

![スクリーンショット 2019-11-28 13 46 57](https://user-images.githubusercontent.com/823277/69778085-5423bd00-11e6-11ea-9aca-69c2ed5aa5f1.png)

Case2: Author line is the longest:

![スクリーンショット 2019-11-28 13 51 44](https://user-images.githubusercontent.com/823277/69778100-6aca1400-11e6-11ea-859e-b1c9c135da05.png)

Maybe some option in vimrc causes this issue.

**Comment by rhysd** [comment]
@weilbith Can I try in the same situation? If ok, please let me know:

- Repository URL you could reproduce this issue
- Git commit hash
- File path you opened

**Comment by rhysd** [comment]
And please check if you set `g:git_messenger_max_popup_width`.

```
:echo g:git_messenger_max_popup_width
```

**Comment by weilbith** [comment]
Hey, thanks for you help!

> And please check if you set g:git_messenger_max_popup_width. The default value is v:null

I can confirm that this is not set by myself and the output is the default value.

---

> @weilbith Can I try in the same situation? If ok, please let me know:

Here we go:
  - [poanetwork/blockscout](https://github.com/poanetwork/blockscout)
  - `master`
  - `apps/block_scout_web/assets/css/components/_navbar.scss` 
     - calling it on line `7` places the commit hash on the next line
     - on line `8` it looks fine
     - line `14` shows an example of a NL for the author.

My screen is wide enough. It floating window(s) should by far not reach the maximum possible width.

**Comment by weilbith** [comment]
@rhysd can you reproduce my issue with the given instructions?

**Comment by rhysd** [comment]
Thank you for the information. I'm sorry for the delay, I don't have sufficient time to look into this. But I think I can try this weekend.

**Comment by weilbith** [comment]
Okay, totally fine. Take your time, nothing urgent. :upside_down_face:

**Comment by alfunx** [comment]
@weilbith I could narrow it down to `set foldcolumn=3` (in https://github.com/weilbith/vim-blueplanet/blob/master/options.vim#L127). Removing that fixes this issue, which suggests this option is also set for the popup.

@rhysd A possible (and IMO clean) solution could be to set `'style': 'minimal'` in the configuration for `nvim_open_win()`, e.g. in https://github.com/rhysd/git-messenger.vim/blob/master/autoload/gitmessenger/popup.vim#L108-L115. The `minimal` style is most useful when "displaying a temporary float where the text should not be edited" (from `:h nvim_open_win()`).

**Comment by rhysd** [comment]
@alfunx 

Thank you so much for narrowing down this issue. I could not notice the option because I set `0` to `foldcolumn`. I'm not sure that the option is root cause of this issue, but I could see the unintended line wrapping with `set foldcolumn=3`.

@weilbith 

Would you update this plugin to the latest and check if this issue still happens in your local or not. If it still happens, I'll reopen this issue.

**Comment by weilbith** [comment]
Yes it works like charm now.
@alfunx thanks for your investigation and the fix!
@rhysd thanks for the nice help for this issue. :+1:
