### ISSUE TITLE
Ignore whitespace

### ISSUE THREAD

**Issue by ColinRyan** [rhysd/git-messenger.vim#41]
Hi. Great plugin but I'm having an issue with whitespace and I'd like to add a flag to diff (-w) to fix it. How would I go about doing that?

**Comment by rhysd** [comment]
Do you mean whitespace in diff? And please describe what is issue for you.

**Comment by ColinRyan** [comment]
yea that's correct, the issue I'm having is on windows with WSL. I've found that whitespace is causing several git related plugins to incorrectly diff my files and give me back "This line is not committed yet". I had the same problem in GitGutter and Fugitive andsolved the problem in fugitive's :Gblame by adding "-w" and solved the problem in GitGutter by add "-w" to an argument variable called g:gitgutter_diff_args. I think this flag would work  for git-messenger too if I could pass in the flag somehow. I've been looking through the code but I'm not sure where to make the edits yet :P.

**Comment by alfunx** [comment]
For now you could add `'-w'` at the end of the list of arguments/options for `spawn_git()` at these two locations:

https://github.com/rhysd/git-messenger.vim/blob/master/autoload/gitmessenger/blame.vim#L199 and https://github.com/rhysd/git-messenger.vim/blob/master/autoload/gitmessenger/blame.vim#L349

**Comment by ColinRyan** [comment]
Thanks, @alfunx! I'll do that :)

**Comment by rhysd** [comment]
ok, how about adding a variable to specify extra arguments for `git diff`?

```vim
let g:git_messenger_extra_diff_args = '-w'
```

**Comment by ColinRyan** [comment]
Sounds like a good idea to me. I was about to fork and do just that.

**Comment by ColinRyan** [comment]
turns out I was wrong about needed to add it to git diff, I needed to add it to git blame. I forked and managed to get it working with a variable as you suggested @rhysd. Let me know if you want a PR.

**Comment by rhysd** [comment]
@ColinRyan Would you make a pull request?

**Comment by wookayin** [comment]
See 7c123e5 (added in 2019-12-18)

`g:git_messenger_extra_blame_args`
