### ISSUE TITLE
popup mappings don't work

### ISSUE THREAD

**Issue by MeisterTea** [rhysd/git-messenger.vim#52]
Pressing any of the default mapping keys just do the default neovim action. (e.g: o sets the insert mode and add a newline)

Any idea?

**Comment by rhysd** [comment]
Please describe more about what you tried. From the short description, I can say nothing. Confirm `:GitMessenger` command is available to check this plugin was properly loaded by your plugin manager.

**Comment by ylmrx** [comment]
You need to switch to the pop up (C-w ...).

**Comment by rhysd** [comment]
To move into popup, please repeat the same mapping after opening popup.

Let's say `<Leader>gm` is mapped to `:GitMessenger` (it's default behavior),

1. `<Leader>gm` opens popup window
2. `<Leader>gm` again moves cursor into popup window
3. You can use `o`, `O`, `d`, `D`, `q`, ... local mappings within the popup

Please see documentation for more details.

**Comment by MeisterTea** [comment]
it works fine, thank's
