### ISSUE TITLE
Preview closed immediately after it opened on Vim 8.2

### ISSUE THREAD

**Issue by tmm** [rhysd/git-messenger.vim#54]
Similar to what @voldikss pointed out in #16, when I use `:GitMessenger` or `<Leader>gm`, the preview opens, then immediately closes. Made a video:

[![asciicast](https://asciinema.org/a/gHd5GnNJbtA8ChC21mpELrY6y.svg)](https://asciinema.org/a/gHd5GnNJbtA8ChC21mpELrY6y)

Happy to provide any other information!

**Comment by rhysd** [comment]
I'm sorry for the delay. And thank you for the screencast. It's very helpful.

I updated my MacVim to v8.2.319 but could not reproduce this. `:GitMessenger` showed preview window and did not close immediately. Would you tell me your OS and version of Vim?

**Comment by tmm** [comment]
No worries! Here's everything:

- `macOS Catalina 10.15.1 19B88 x86_64`
- `Vim 8.2 (2019 Dec 12, compiled Mar  4 2020 22:41:50)`

I have experienced this issue on two different machines in a few repositories. The one from the video is public https://github.com/tmm/mute.vc

- File `mute.vc/layouts/default.vue`
- Line 26
- Direct link https://github.com/tmm/mute.vc/blob/master/layouts/default.vue#L26
- SHA `37b8ea87a5a41c37a7b8a723cc9bffd1f9bb909d` (latest commit on master)

 Thanks for looking into it!


https://github.com/tmm/mute.vc/blob/master/layouts/default.vue#L26

**Comment by rhysd** [comment]
> Vim 8.2 (2019 Dec 12, compiled Mar 4 2020 22:41:50)

Would you also share the detailed Vim information with following command? I want to align patch version of Vim.

```
vim --not-a-term -u NONE -c version -c quit | pbcopy
```

**Comment by stefanhofman** [comment]
I have the same issue, I figured out it has something to do with updatetime. The preview stays open for the amount of time set at updatetime. I suspect the issue might be the same as here: https://github.com/pechorin/any-jump.vim/issues/25

Hope this helps.

**Comment by rhysd** [comment]
Thanks for the information. I tried `updatetime=4000`, `updatetime=1000`, `updatetime=100`, but none of them did not reproduce this issue. I guess there would be combination of other conditions.

**Comment by tmm** [comment]
```
[?1049h[>4;2m[?1h=[?2004h[1;50r[?12h[?12l[22;2t[22;1t[27m[29m[m[H[2J[50;1H
[?25lVIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  4 2020 22:41:50)

macOS version

Included patches: 1-350

Compiled by Homebrew

Huge version without GUI.  Features included (+) or not (-):

+acl[15C+cmdline_hist      +ex_extra[10C+keymap[12C-mouse_gpm[9C+persistent_undo   +spell[13C+timers[12C-X11

+arabic[12C+cmdline_info      +extra_search      +lambda[12C-mouse_jsbterm     +popupwin[10C+startuptime[7C+title[13C-xfontset

+autocmd[11C+comments[10C-farsi[13C+langmap[11C+mouse_netterm     +postscript[8C+statusline[8C-toolbar[11C-xim

+autochdir[9C+conceal[11C+file_in_path      +libcall[11C+mouse_sgr[9C+printer[11C-sun_workshop      +user_commands     -xpm

-autoservername    +cryptv[12C+find_in_path      +linebreak[9C-mouse_sysmouse    +profile[11C+syntax[12C+vartabs[11C-xsmp

-balloon_eval      +cscope[12C+float[13C+lispindent[8C+mouse_urxvt[7C-python[12C+tag_binary[8C+vertsplit[9C-xterm_clipboard

+balloon_eval_term +cursorbind[8C+folding[11C+listcmds[10C+mouse_xterm[7C+python3[11C-tag_old_static    +virtualedit[7C-xterm_save

-browse[12C+cursorshape[7C-footer[12C+localmap[10C+multi_byte[8C+quickfix[10C-tag_any_white     +visual

++builtin_terms    +dialog_con[8C+fork()[12C+lua[15C+multi_lang[8C+reltime[11C-tcl[15C+visualextra

+byte_offset[7C+diff[14C+gettext[11C+menu[14C-mzscheme[10C+rightleft[9C+termguicolors     +viminfo

+channel[11C+digraphs[10C-hangul_input      +mksession[9C+netbeans_intg     +ruby[14C+terminal[10C+vreplace

+cindent[11C-dnd[15C+iconv[13C+modify_fname      +num64[13C+scrollbind[8C+terminfo[10C+wildignore

-clientserver      -ebcdic[12C+insert_expand     +mouse[13C+packages[10C+signs[13C+termresponse      +wildmenu

+clipboard[9C+emacs_tags[8C+job[15C-mouseshape[8C+path_extra[8C+smartindent[7C+textobjects[7C+windows

+cmdline_compl     +eval[14C+jumplist[10C+mouse_dec[9C+perl[14C-sound[13C+textprop[10C+writebackup

   system vimrc file: "$VIM/vimrc"

     user vimrc file: "$HOME/.vimrc"

 2nd user vimrc file: "~/.vim/vimrc"

      user exrc file: "$HOME/.exrc"

[7Cdefaults file: "$VIMRUNTIME/defaults.vim"

  fall-back for $VIM: "/usr/local/share/vim"

Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1

Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim

[7C-lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl

[49;180H/[50;1H5.30.1/lib/perl5/5.30.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -l

[49;180Hp[50;1Hython3.7m -framework CoreFoundation  -lruby.2.7
[?2004l[23;2t[23;1t
[?2004l[?1l>[?25h[>4;m[?1049l
```

**Comment by xulongwu4** [comment]
Hi, in my case `set updatetime=100` causes the popup window closes immediately. I tried a minimal vimrc and can confirm that this is the single condition to trigger this behavior. I am using vim 8.2 on linux.

**Comment by ixandidu** [comment]
You can [configure the behavior of this plugin using global variables](https://github.com/rhysd/git-messenger.vim#variables).

To solve this issue, you can configure one of the following configuration:

1. Keep the popup window open on cursor movement ([ref](https://github.com/rhysd/git-messenger.vim#ggit_messenger_close_on_cursor_moved-default-vtrue)):

        let g:git_messenger_close_on_cursor_moved = v:false

2. Move the cursor to the popup window ([ref](https://github.com/rhysd/git-messenger.vim#ggit_messenger_always_into_popup-default-vfalse)): 

        let g:git_messenger_always_into_popup = v:true

Since I mostly want to browse the diff, I prefer to move the cursor to the popup window and also configure it to includes the diff in the popup window:

```vim
let g:git_messenger_always_into_popup = v:true
let g:git_messenger_include_diff = "current"
```

Configuring the cursor to go into the popup window will automatically close the preview window once you move the cursor out of the preview window.

**Comment by tmm** [comment]
@ixandidu that works for me! thanks!

**Comment by rhysd** [comment]
This was fixed by 9ffaaaf. A workaround is no longer necessary.

**Comment by sheerun** [comment]
I've just installed git-messenger and it still happens

**Comment by rhysd** [comment]
@sheerun What happens if `let g:git_messenger_close_on_cursor_moved = v:false` in your vimrc?

**Comment by sheerun** [comment]
It actually doesn't close (why isn't the default), but if I do `:GitMessenger` on some other line, then it just jumps to scratch window instead of telling the commit of other line

https://asciinema.org/a/WPuXTaUo6XYazF423EEsu81WG

**Comment by rhysd** [comment]
> It actually doesn't close

It means that some other plugin causes `CursorMoved` event when leaving the preview window. git-messenger.vim closes preview window when cursor is moved hence user doesn't care about closing window. Logic to open preview window is as follows:

1. Open preview window
2. Enter the window
3. Write contents
4. Leave the window

when 4., some event like `BufEnter` is triggered. If some other plugin hooks the event and does something which triggers `CursorMoved`, git-messenger.vim closes preview window. Actually it does not happen in my environment. So some plugin which you installed and I didn't install causes this issue.

> if I do :GitMessenger on some other line, then it just jumps to scratch window instead of telling the commit of other line

I see. With current implementation, you need to close the preview window by yourself. You may prefer `let g:git_messenger_always_into_popup = v:true`.

**Comment by sheerun** [comment]
I've ended up using following mapping, works fine:

`:nmap <silent><Leader>g :call popup_atcursor(split(system("git log -n 1 -L " . line(".") . ",+1:" . expand("%:p")), "\n"), { "padding": [1,1,1,1], "pos": "botleft", "wrap": 0 })<CR>`

**Comment by sheerun** [comment]
It seems I can even get highlighting with `nmap <silent><Leader>g :call setbufvar(winbufnr(popup_atcursor(split(system("git log -n 1 -L " . line(".") . ",+1:" . expand("%:p")), "\n"), { "padding": [1,1,1,1], "pos": "botleft", "wrap": 0 })), "&filetype", "git")<CR>`

**Comment by rhysd** [comment]
This might be related to this issue. git-messenger.vim closes a preview window when cursor moves, but sometimes `CursorMoved` seems triggered unexectedly for some reason.

https://github.com/vim/vim/issues/2053

**Comment by unphased** [comment]
@sheerun Your bind is awesome, but it does not work under neovim. Just fyi.
