### ISSUE TITLE
Not inside a git repository error on windows

### ISSUE THREAD

**Issue by blayz3r** [rhysd/git-messenger.vim#55]
Git messenger cant seem to find the .git file, no idea why
 _**s:find_dotgit**_ and **_gitmessenger#git#root_dir_**  return the correct result outside the plugin.

![image](https://user-images.githubusercontent.com/12205650/77463873-afed0400-6ddc-11ea-97fa-2dc565454dc7.png)

![image](https://user-images.githubusercontent.com/12205650/77463712-73b9a380-6ddc-11ea-83fe-d0e12c48ce30.png)

**Comment by ParhamNikdouz** [comment]
I have the same issue in VIM 8.1 on ubuntu.
