### ISSUE TITLE
Feature request: add committer date and date format configuration

### ISSUE THREAD

**Issue by xaljer** [rhysd/git-messenger.vim#62]
sometimes committer time is more meaningful, because it's the time when patch into team's history.

**Comment by rhysd** [comment]
d765028 and f1e133c solved this issue.

Here is a screenshot when author date and committer date are different.

<img width="634" alt="スクリーンショット 2020-07-29 22 44 05" src="https://user-images.githubusercontent.com/823277/88807907-32535d80-d1ed-11ea-8798-81f2ed6bedd2.png">
