### ISSUE TITLE
unmap inside the popup window

### ISSUE THREAD

**Issue by kevinhwang91** [rhysd/git-messenger.vim#63]
I have remapped `d` to scroll down the half-page in my workflow, but git-messenger.vim can't unmap `d` inside popup.

filetype event didn't work because it was triggered before mapping key inside the popup window.

**Comment by rhysd** [comment]
https://github.com/rhysd/git-messenger.vim#configuration-for-popup-window

Does unmapping the mappings on `FileType gitmessengerpopup` event work?

**Comment by rhysd** [comment]
Yes, currently the default mappings cannot be overriden. I'll fix this.

**Comment by rhysd** [comment]
Now below should work.

```vim
function! s:setup_git_messenger_popup() abort
    nunmap <buffer>d
endfunction
autocmd FileType gitmessengerpopup call <SID>setup_git_messenger_popup()
```
