### ISSUE TITLE
[Neovim] diff shows Ansi escape sequences

### ISSUE THREAD

**Issue by jdsutherland** [rhysd/git-messenger.vim#64]
![image](https://user-images.githubusercontent.com/5385846/90555376-1c7dec00-e14c-11ea-8b92-fd03b26b6cf6.png)

I think the problem comes from `.gitconfig`:
```conf
[color]
  ui = always
```

Is it possible to make this compatible with git-messenger?

Side note: it'd be great if the diff could work with https://github.com/so-fancy/diff-so-fancy. I'm not sure if it's possible since it uses git pager.

**Comment by jdsutherland** [comment]
Sorry, `color.ui = auto` fixes this.

**Comment by rhysd** [comment]
Did you set `color.ui = always` in config? I think it's better that git-messenger.vim adds `--no-color` on running Git commands.

**Comment by jdsutherland** [comment]
Yeah, I previous had `color.ui = always` which caused the ANSI escape to show but when I switch git config to `color.ui = auto`, the color displays as expected.

**Comment by rhysd** [comment]
OK, I'll add `--no-color` to args of `git` commands. Thanks.
