### ISSUE TITLE
[Feature Request] View word-diff version of commit

### ISSUE THREAD

**Issue by MisanthropicBit** [rhysd/git-messenger.vim#66]
I usually find it very useful to see the --word-diff of a commit instead of the normal diff.

I have a working (albeit hacked together) version working that passes the default `--word-diff=plain` to the git arguments in `s:blame__reveal_diff` and added some additional syntax stuff to highlight the word-diff. One issue that popped up is that lines can become quite long as seen in the screenshot.

For starters, I can clean everything up and submit a pull request if you agree this would be a useful feature?
 
<img width="819" alt="Screenshot 2020-12-22 at 10 23 16" src="https://user-images.githubusercontent.com/1846147/102872715-651e1c80-4440-11eb-9e5e-7da487a34cd9.png">

**Comment by rhysd** [comment]
Yes, I agree to add the feature if the implementation looks good to me. You already seem to have implementation. Please try to make a PR as-is. I can review it.

**Comment by MisanthropicBit** [comment]
Great! I'll clean up the implementation and submit a PR.
