### ISSUE TITLE
error when using git-messenger, -C option is not available.

### ISSUE THREAD

**Issue by jdhao** [rhysd/git-messenger.vim#67]
Version info: neovim 0.5.0
git:  1.8.3.1
system: CentOS 7.4

When using the default mapping `<leader>gm` to show message a line: I am seeing the following error:

> git-messenger: Unknown option: -C usage: git ....

I think it is because the git version is not so up to date.  Can we use `--git-dir` and `--work-tree` option instead of `-C`?

**Comment by rhysd** [comment]
That's too old Git. Can you install more recent one? I'll check which is the minimum Git version and add it to documentation.

**Comment by rhysd** [comment]
> Can we use --git-dir and --work-tree option instead of -C?

It might be possible. But I did not try since almost all systems have newer Git.

**Comment by rhysd** [comment]
`-C` was introduced by Git 1.8.5: https://github.com/git/git/blob/4a0de43f4923993377dbbc42cfc0a1054b6c5ccf/Documentation/RelNotes/1.8.5.txt#L115-L116

**Comment by jdhao** [comment]
I think a lot of people are still using CentOS 7.4 as their server. The default git version is 1.8.3. Since i do not have root rights, it is hard to install git from source either.

**Comment by rhysd** [comment]
If some other people are facing this issue, please leave comments to this issue. If there are several comments left, I'll consider to support the older Git.
