### ISSUE TITLE
Add highlight border color variable

### ISSUE THREAD

**Issue by ecosse3** [rhysd/git-messenger.vim#73]
Hi,

It would be nice if you add the ability to set highlight border color. I use this plugin pretty often and I've started using [lspsaga.nvim](https://github.com/glepnir/lspsaga.nvim) so I would like to set the colors of git-messenger to be similar to all my IDE.

Linking background color works as expected but without border, it's hard to recognize popup.

LspSaga border style:
![image](https://user-images.githubusercontent.com/17691791/111039215-2b502700-842d-11eb-9665-5691b5349666.png)

Current git-messenger popup (hard to see):
![image](https://user-images.githubusercontent.com/17691791/111039226-399e4300-842d-11eb-96b7-547784594d81.png)

Thanks!

**Comment by rhysd** [comment]
My recommendation is setting different background color from `Normal` for `NormalFloat` or `gitmessengerPopupNormal`.

My recommended config is below:

```vim
autocmd ColorScheme * highlight link gitmessengerPopupNormal CursorLine
```

Does this work fine in your environment? Or do you still want border?

**Comment by phelipetls** [comment]
Neovim now has an API to add border to floating windows. Would it be easy to add configuration for this? For example, `let g:git_messenger_border = "single"` to pass `{ border: "single" }` to `nvim_open_win`.

**Comment by rhysd** [comment]
Looks good. I didn't know Neovim's float window supports borders since it had not supported it when I'd implemented this plugin.

**Comment by rhysd** [comment]
@ecosse3 @phelipetls I tried border window and felt that margin was not necessary when border existed. So I tried to implement to make margin configurable at [margin-removable branch](https://github.com/rhysd/git-messenger.vim/tree/margin-removable).

Do you think you want this feature?

<img width="525" alt="スクリーンショット 2021-04-16 18 28 07" src="https://user-images.githubusercontent.com/823277/115004583-eadb4180-9ee1-11eb-8605-3debb6a062e7.png">

compared to

<img width="552" alt="スクリーンショット 2021-04-16 18 31 41" src="https://user-images.githubusercontent.com/823277/115004672-021a2f00-9ee2-11eb-8715-1b7377c096c0.png">

**Comment by phelipetls** [comment]
Yes, that'd be great! Thanks for the plugin.

**Comment by cloggier** [comment]
I prefer with margins. :)

**Comment by rhysd** [comment]
@phelipetls @cloggier 

Thank you for your feedbacks. Since adding/removing margin is separate configuration from floating window options, it's possible to add both border and margin. I'll merge this into master after adding some tests.
