### ISSUE TITLE
popup commit body sometimes shows CRLF ^M

### ISSUE THREAD

**Issue by jdsutherland** [rhysd/git-messenger.vim#75]
Sometimes the commit body shows `^M`:

![image](https://user-images.githubusercontent.com/5385846/113925940-72b5a300-97a0-11eb-82d3-f20e939c0b37.png)

I don't get the `^M` using git.

**Comment by jdsutherland** [comment]
I'm not sure if this is an issue with my config or the plugin, but I don't see the `^M` in other contexts. I used the following as a quick fix:

```
syntax match hideControlM "\r$" conceal
setlocal concealcursor=nv
```

**Comment by rhysd** [comment]
What is your operating system and how did you install Git?

**Comment by rhysd** [comment]
I'll look into this tonight.

**Comment by rhysd** [comment]
@jdsutherland With 4621dd8, now git-messenger.vim considers `\r\n` on splitting lines from Git. Can you check if this issue is addressed?

**Comment by jdsutherland** [comment]
The `^M` still show up after pulling in the changes.

I'm on macOS with `autocrlf = input`.

Here's the sample commit: https://github.com/tootsuite/mastodon/commit/7880671f3527b80de891053beaeae4a8a22c8c58. The `^M` only show up in certain repos.

**Comment by rhysd** [comment]
Thanks for confirming that.

The commit might have CR in its message. Does `git show {hash}` in your terminal show CR in commit message?

Anyway, I think removing `\r` in commit message by git-messenger.vim would be fine.

**Comment by rhysd** [comment]
I'll check the repository in my side.

**Comment by rhysd** [comment]
OK, I could reproduce this with Neovim. It did not reproduce on Vim, so it seems an issue specific to Neovim's floating window. I'll look into it.

**Comment by jdsutherland** [comment]
Sorry, I should have mentioned I'm using Neovim. Glad we've isolated it.

**Comment by rhysd** [comment]
This actually did not seem an issue of git-messenger.vim. The commit message actually contains `\r`. I guess the author's text editor used `\r\n` for newlines to write the message.

However, it is not useful to show `^M` in message. So 8775f30 removes trailing `\r` in the commit message when getting a commit body from `git log -n 1`. I confirmed no longer `^M` shows up in my local.
